Adding check for consistency in land cover and soil
NOAA-OWP/noah-owp-modular pull request #100
Opened 2024-02-22 15:55 UTC by GreyEvenson-NOAA

2024-03-26 17:47 UTC, PhilMiller commented on src/RunModule.f90
> +      if(any(err_grid.eq.1)) then; write(*,'(A,i2,A)') 'ERROR: one or more grid cells have an ice land cover (vegtyp = ',parametersgrid%ISICE,') and a non-ice soil type (isltyp != 16)'; stop; end if
The code could de-allocate `err_grid` here, since it's not going to be used later in the simulation

2024-03-26 19:18 UTC, drakest123 requested changes
If possible, report problematic grid cell locations rather than the fact that there is/are problematic grid cells.

2024-03-26 20:27 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +      if(any(err_grid.eq.1)) then; write(*,'(A,i2,A)') 'ERROR: one or more grid cells have an ice land cover (vegtyp = ',parametersgrid%ISICE,') and a non-ice soil type (isltyp != 16)'; stop; end if
Appreciate the catch, @PhilMiller

2024-04-09 13:20 UTC, GreyEvenson-NOAA commented
Thanks for the review @drakest123. I went ahead and add locational information to the error messages.

2024-04-09 13:26 UTC, GreyEvenson-NOAA commented
@SnowHydrology Do you think this PR's checks are too restrictive? Here, we're requiring grid cells that have `ice` land cover to have `ice` soils as well.

2024-04-12 18:39 UTC, SnowHydrology requested changes
This looks good with one exception: using `stop` prevents the framework from returning useful error information. Instead, I'd recommend using `return` and then having the initialize routine return `BMI_FAILURE`. See examples [here](https://github.com/SnowHydrology/noah-owp-modular/blob/f939e07ba45397bbc697f83cedbcbb19ad4c2256/bmi/bmi_noahowp.f90#L272) and [here](https://github.com/SnowHydrology/noah-owp-modular/blob/f939e07ba45397bbc697f83cedbcbb19ad4c2256/src/EnergyModule.f90#L309).

2024-05-22 19:48 UTC, GreyEvenson-NOAA commented
Note: I'm leaving the `stop` statements as-is with the assumption that the issue will be corrected by PR #108.

2024-05-22 19:51 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +    integer, dimension(2)                   :: err_indices        ! to hold ix, iy for err_grid
Note: it may be preferable to move these error-related objects to the ErrorCheckModule if PR #108 elects to make greater use of that module for error checking and messaging purposes.

2024-05-22 19:52 UTC, merged