Dev 5
NOAA-OWP/noah-owp-modular pull request #71
Opened 2023-06-21 15:47 UTC by GreyEvenson-NOAA

2023-06-27 13:59 UTC, SnowHydrology commented
@GreyEvenson-NOAA, please provide an illustrative title for the pull request and include a description (see https://github.com/NOAA-OWP/noah-owp-modular/pull/57 as an example, or this from CFE is even better https://github.com/NOAA-OWP/cfe/pull/62).

2023-06-27 20:31 UTC, SnowHydrology commented
Next steps:

- Rebuild code structure to follow original Noah-OWP-Modular codebase
  - This facilitates separation of concerns, continues the level of modularization previously implemented, and enables version tracking of file changes (harder to do when files move/change names)
  - More granular modularization also makes unit testing easier
  - Move new files from `driver/` to `src/`
  - Move main program back to `driver/` and keep original name
- Re-implement helper functions that wrap other functions/subroutines
  - Example is `initialize_from_file`, which got replaced by `NoahowpReadNamelistModule` in this PR
  - Move code from `driver/NoahowpReadNamelistModule.f90` back to `src/NamelistRead.f90`
    - Remember separation of concerns: `NamelistRead.f90` should read the namelist and allocate the namelist variables (it should do no additional function calling or initialization, that will get wrapped into `initialize_from_file` in `RunModule.f90` as done previously)

2023-07-13 14:06 UTC, SnowHydrology commented on bmi/bmi_noahowp.f90
> +   case('SFCPRS')
@GreyEvenson-NOAA, my understanding is that each variable does not employ a unique grid ID. Rather, the ID (i.e., `grid = 1`) is unique to the variable's spatial discretization or configuration. For example, if you have a scalar value like a parameter that is constant in space, it would get one grid ID. If you have another scalar parameter, it would have the same grid ID as the first. Conversely, if you then have an array like a regular grid of a hydrologic flux, then it would have a different grid ID than the scalar parameters. Other states and fluxes on the same array/grid would have the same ID as well. In this hypothetical, we could have `grid = 0` for the scalars and `grid = 1` for the arrays.

@peckhams, can you confirm this is correct? Or, if not, educate me on the use of `get_var_grid`?

2023-07-13 17:51 UTC, SnowHydrology requested changes
@GreyEvenson-NOAA, this is looking really good! Please take a look at my comments and let me know if you have any questions. There aren't too many requested changes, but they'll need to be handled before merging. Thanks

2023-07-13 17:51 UTC, SnowHydrology commented on src/DomainGridType.f90
> +    real, allocatable, dimension(:,:)     :: ZREF              ! measurement height of wind speed (m)
Should be scalar, same value across domain

2023-07-13 17:51 UTC, SnowHydrology commented on src/DomainGridType.f90
> +      allocate(this%ZREF            (n_x,n_y))
scalar

2023-07-13 17:51 UTC, SnowHydrology commented on src/DomainGridType.f90
> +      this%ZREF(:,:)           = huge(1.0)
scalar

2023-07-13 17:51 UTC, SnowHydrology commented on src/DomainGridType.f90
> +      this%ZREF(:,:)            = namelist%ZREF
scalar

2023-07-13 17:51 UTC, SnowHydrology commented on src/DomainGridType.f90
> +module DomainGridType
@GreyEvenson-NOAA I'd like to see `n_x`, `n_y`, and other variables that describe the model domain be part of the `domaintype`.

2023-07-13 17:51 UTC, SnowHydrology commented on src/DomainType.f90
>  module DomainType
Add `n_x`, `n_y` and others here (per previous comment on `DomainGridType.f90`.

2023-07-13 17:51 UTC, SnowHydrology commented on src/NamelistRead.f90
> +    this%n_x = 2
@GreyEvenson-NOAA To avoid any hidden problems later, please move the hardcoding of n_x and n_y to the program file or add them as entries in the namelist (probably easier to do the former than latter).

2023-07-13 17:51 UTC, SnowHydrology commented on src/OptionsGridType.f90
> +module OptionsGridType
@GreyEvenson-NOAA the way this file is configured, we can set different model options in each grid cell. I'm not certain we want to support that.

2023-07-13 17:51 UTC, SnowHydrology commented on src/OptionsType.f90
>  module OptionsType
@GreyEvenson-NOAA, see previous comment on `OptionsGridType.f90`. We just might want scalar model options.

2023-07-13 17:51 UTC, SnowHydrology commented on src/OptionsTypeTransfer.f90
> +module OptionsTypeTransfer
@GreyEvenson-NOAA, see previous comment on `OptionsGridType.f90`. We just might want scalar model options.

2023-07-13 17:51 UTC, SnowHydrology commented on src/ParametersGridType.f90
> +    real                                              :: refkdt                    !
I think we want these following params to be vary-able in space (i.e., put them on the grid)

2023-07-13 17:51 UTC, SnowHydrology commented on src/ParametersGridType.f90
> +    real                                              :: slope                     ! drainage parameter
Same here

2023-07-13 17:51 UTC, SnowHydrology commented on src/ParametersGridType.f90
> +module ParametersGridType
@GreyEvenson-NOAA Please go through and double-check all the variables that should be on a grid and those that should be scalars. I note a couple in my comments below, but there are probably more that need confirming.

2023-07-13 17:51 UTC, SnowHydrology commented on src/ParametersTypeTransfer.f90
> +module ParametersTypeTransfer
@GreyEvenson-NOAA see previous comment on double-checking grid vs. scalar params

2023-07-13 17:51 UTC, SnowHydrology commented on src/RunModule.f90
> +    type (noahowpgrid_type), intent (inout) :: model
@GreyEvenson-NOAA I believe this should still be `intent(out)` as the instance of `noahowpgrid_type` is created by the `initialize_from_file` function.

2023-07-13 17:51 UTC, SnowHydrology commented on src/RunModule.f90
> +        domaingrid%zsnso(:,:,ii) = 0.0
Confirm if loop is needed versus just `domaingrid%zsnso(:,:,-namelist%nsnow+1:0) = 0.0`

2023-07-13 17:51 UTC, SnowHydrology commented on src/RunModule.f90
> +        domaingrid%zsnso(:,:,ii) = namelist%zsoil(ii)
Same

2023-07-13 17:51 UTC, SnowHydrology commented on src/RunModule.f90
> +    !I think this needs to be done here rather than in UtilitiesMain if NGEN isn't doing forcing
I'm not sure I understand this comment, please clarify

2023-07-13 17:51 UTC, SnowHydrology commented on src/RunModule.f90
> +    forcinggrid%UU(:,:)     = read_UU
Add comments and a `TODO` clarifying this is a temporary hack for grid testing

2023-07-13 17:51 UTC, SnowHydrology commented on src/RunModule.f90
> +        ! Reinitialize noahowp_type variables (unneccesary?)
@GreyEvenson-NOAA Did you test the code with/without re-initializing? That could save some runtime if it doesn't matter

2023-07-14 14:05 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +        domaingrid%zsnso(:,:,ii) = 0.0
Change made. This works.

2023-07-14 14:24 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +        domaingrid%zsnso(:,:,ii) = namelist%zsoil(ii)
This seems like it should work but does not. I tried `domaingrid%zsnso(:,:,1:namelist%nsoil) = namelist%zsoil(1:namelist%nsoil)` and `domaingrid%zsnso(:,:,1:namelist%nsoil) = namelist%zsoil(:)` and `domaingrid%zsnso(:,:,1:namelist%nsoil) = namelist%zsoil` but get `Error: Incompatible ranks 3 and 1 in assignment at (1)`

2023-07-14 16:08 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +    !I think this needs to be done here rather than in UtilitiesMain if NGEN isn't doing forcing
Please disregard this comment. Comment removed.

2023-07-14 16:09 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +    forcinggrid%UU(:,:)     = read_UU
The concerning comment was removed. No further action is needed.

2023-07-14 16:42 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +        ! Reinitialize noahowp_type variables (unneccesary?)
I moved calls to subroutines that initialize the local instance of `noahowp_type` to immediately prior to the spatial loop. This allows us to initialize/allocate the `noahowp_type` variables but do this only once rather than for every grid cell.

After moving calls to the `noahowp_type` initialization routines to prior to the spatial loop, I recompiled and re-executed `/test/analysis/compare_outputnc.py `and found that all tests were passed. I also re-executed `/test/noahowp_test.exe` an observed that the program's output was correct.

2023-07-14 18:04 UTC, GreyEvenson-NOAA commented on bmi/bmi_noahowp.f90
> +   case(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
Change adopted.

2023-07-14 18:05 UTC, GreyEvenson-NOAA commented on bmi/bmi_noahowp.f90
> +   case(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
Change made.

2023-07-14 18:06 UTC, GreyEvenson-NOAA commented on bmi/bmi_noahowp.f90
> +   case(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
Change made.

2023-07-14 18:07 UTC, GreyEvenson-NOAA commented on bmi/bmi_noahowp.f90
> +   case(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
Change made.

2023-07-14 18:23 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +    type (noahowpgrid_type), intent (inout) :: model
Change made.

2023-07-14 18:34 UTC, GreyEvenson-NOAA commented on src/OptionsGridType.f90
> +module OptionsGridType
Got it. I revised OptionsGridType.f90 and OptionsTypeTransfer.f90 so that all options are scalars.

2023-07-14 18:47 UTC, GreyEvenson-NOAA commented on src/OptionsType.f90
>  module OptionsType
Agreed, I copy and pasted the `options_type` variables into `optionsgrid_type` and `OptionsGridType.f90`.

2023-07-14 18:48 UTC, GreyEvenson-NOAA commented on src/OptionsTypeTransfer.f90
> +module OptionsTypeTransfer
I revised OptionsTypeTransfer.f90 accordingly.

2023-07-14 19:48 UTC, GreyEvenson-NOAA commented on driver/OutputModule.f90
> +#endif
Apologies. I think this was an artifact of the original version of the PR's code and my attempts to get that running with NGEN. I revised `driver/OutputModule.f90` to have one `#ifndef NGEN_OUTPUT_ACTIVE` flag at the beginning of the module and one `#endif` flag at the end of the module.

2023-07-17 12:21 UTC, GreyEvenson-NOAA commented on src/DomainGridType.f90
> +      allocate(this%ZREF            (n_x,n_y))
Change made.

2023-07-17 12:24 UTC, GreyEvenson-NOAA commented on src/DomainGridType.f90
> +      this%ZREF(:,:)           = huge(1.0)
Change made.

2023-07-17 12:24 UTC, GreyEvenson-NOAA commented on src/DomainGridType.f90
> +      this%ZREF(:,:)            = namelist%ZREF
Change made.

2023-07-17 20:22 UTC, GreyEvenson-NOAA commented on src/DomainGridType.f90
> +    real, allocatable, dimension(:,:)     :: ZREF              ! measurement height of wind speed (m)
Change made.

2023-07-18 12:24 UTC, GreyEvenson-NOAA commented on src/DomainType.f90
>  module DomainType
Change made.

2023-07-18 13:31 UTC, GreyEvenson-NOAA commented on bmi/bmi_noahowp.f90
>  !================================ IMPLEMENT WHEN noahowp DONE IN GRID ======================
Removed.

2023-07-19 13:12 UTC, GreyEvenson-NOAA commented on bmi/bmi_noahowp.f90
>    function noahowp_grid_spacing(this, grid, spacing) result (bmi_status)
I implemented `get_grid_spacing`, `get_grid_x`, and `get_grid_y`. 

For `get_grid_spacing`, `dx` and `dy` were added as members of `namelist_type`, `domain_type`, and `domaingrid_type`. I anticipate `dx` and `dy` will be provided by the input netcdf file and will be given to `namelist_type` via a call to `domaingrid_type%InitTransfer(namelist_type)`

2023-07-19 18:36 UTC, GreyEvenson-NOAA commented on src/ParametersGridType.f90
> +    real                                              :: refkdt                    !
Change made. And I revised parametersgrid_type such that most of its member variables have x and y dim indices.

2023-07-19 18:36 UTC, GreyEvenson-NOAA commented on src/ParametersGridType.f90
> +    real                                              :: slope                     ! drainage parameter
Change made. And I revised parametersgrid_type such that most of its member variables have x and y dim indices.

2023-07-19 18:38 UTC, GreyEvenson-NOAA commented on src/ParametersGridType.f90
> +module ParametersGridType
I revised `parametersgrid_type` such that most of its member variables have x and y dim indices.

2023-07-19 21:22 UTC, GreyEvenson-NOAA commented
I believe we're ready for you to have another look, @SnowHydrology. 

In my revisions to the `parametersgrid_type` member variables, I tried to error on the side of including x and y dim indices as I believe you mentioned in a call that member variables that do not include x and y dim indices would be the exception rather than the rule. However, please let me know if I misunderstood.

Following all revisions to the PR, I re-ran /test/analysis/compare_outputnc.py and its output was: [output_compare_outputnc.txt](https://github.com/NOAA-OWP/noah-owp-modular/files/12100220/output_compare_outputnc.txt). I also re-ran /test/noahowp_test.exe and its output was: [noahowp_test_output.txt](https://github.com/NOAA-OWP/noah-owp-modular/files/12100062/noahowp_test_output.txt)

I clicked on the button to 'Resolve conversation' for your comments that were easy fixes with little ambiguity. However, please let me know if I should leave those conversations open or have other feedback regarding my use of github.

2023-07-25 20:22 UTC, GreyEvenson-NOAA commented on src/DomainGridType.f90
> +    real                                  :: lat               ! latitude (°)
Makes sense. Reverting changes here and in src/DomainTypeTransfer.f90

2023-07-25 20:22 UTC, GreyEvenson-NOAA commented on src/DomainTypeTransfer.f90
> +    domain%lat = domaingrid%lat
Change made.

2023-07-26 13:11 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
> +
I moved the hardcoding of n_x, n_y, dx, and dy to test/noahowp_driver_test.f90 and driver/NoahModularDriver.f90. To make this happen, it seemed that I needed to make a choice between exposing n_x, n_y, dx, and dy via BMI functions or simply making bmi%model (i.e., bmi_noahowp%noahowpgrid_type) public. I elected to make bmi%model public for testing purposes and made a note to make it private after these variable values are read-in via the netcdf file in subsequent PRs. However, maybe there is an easier / better means of completing this move? Or would you prefer exposing these variables via BMI?

2023-07-26 17:18 UTC, GreyEvenson-NOAA commented on bmi/bmi_noahowp.f90
>    function noahowp_grid_x(this, grid, x) result (bmi_status)
Apologies, these were not correct. I revised these subroutines to use `domaingrid_type%lat` and `domaingrid_type%lon`

2023-07-27 17:42 UTC, SnowHydrology commented on src/RunModule.f90
> +
@GreyEvenson-NOAA, I see what you're saying. I was wrong to think we could move this to the test program file. We'll leave the hard-coded values here for now and remove them on the next PR.

2023-07-27 17:44 UTC, SnowHydrology approved these changes

2023-07-27 17:46 UTC, merged