Add functionality to read gridded domain info and land use from input netcdf file
NOAA-OWP/noah-owp-modular pull request #74
Opened 2023-08-01 16:45 UTC by GreyEvenson-NOAA

# PURPOSE

This PR modifies the gridded version of the Noah-OM model to read gridded domain info (e.g., `n_x`, `n_y`, `dx`, and `dy`) and land use (i.e., `vegtyp`) values from a netcdf input file. Subsequent PRs will add functionality to read additional gridded model variables (e.g., soils, slope, etc).

# ADDITIONS

This PR adds a new module (i.e., `GridlistRead.f90`) to the code base. The new module defines a new derived data type (i.e., `gridlist_type`) which has one type-bound subroutine (i.e., `ReadGridlist`), which contains all code needed to open and read an input netcdf file. The `gridlist_type` is intended to mimic the role of the existing `namelist_type` but contain only gridded model input data (e.g., land use data) and associated attributes (e.g., `nveg`) to be read-in from the input netcdf file. 

The newly defined derived data type, `gridlist_type`, was made a member of the `noahowpgrid_type`, as defined in `RunModule.f90`. 

Immediately following a call to `namelist_type%ReadNamelist` in `initialize_from_file`, `gridlist_type%ReadGridlist` is called with the populated `namelist_type` given as an argument. The `ReadGridlist` subroutine then opens the netcdf file and looks for required dimensions, variables, and attributes; reads variables and attributes while checking for errors; then finally transfers the read-in variables and attributes to the `gridlist_type`.

Following the call to `gridlist_type%ReadGridlist`, the populated instance of `gridlist_type` is given as an argument (often alongside the `namelist_type`) to the initialization subroutines for other derived type members of `noahowpgrid_type` to facilitate allocation of allocatable arrays and transfer read-in variables and attributes from the `gridlist_type`.

`data/netcdf_dummy.nc` was added as a dummy netcdf input file to facilitate testing. The dataset contains two dimensions (`Latitude` and `Longitude`). The dimension `Latitude` has the attribute `dy` and the dimension `Longitude` has the attribute `dx`. The dataset contains three variables (`Latitude`, `Longitude`, and `vegtyp`). The variable `Latitude` is a one-dimensional array with dimension `Latitude` containing the latitude coordinates of all grid cells/nodes along the y-axis edge of a uniform rectilinear grid. The length of the `Latitude` variable is `n_y`. The variable `Longitude` is a one-dimensional array with dimension  `Longitude` containing the longitude coordinates of all grid cells/nodes along the x-axis edge of a uniform rectilinear grid. The length of the `Longitude` variable is `n_x`. The variable `vegtyp` has two dimension (`Latitude` and `Longitude`) and has the attributes `nveg` and `veg_class_name`.

`test/analysis/create_dummy_netcdf.py` was added to create `data/netcdf_dummy.nc`. This script was added to facilitate changes changes to the organization and contents of the input netcdf file per PR feedback.

# CHANGES

`namelist.input` was modified to remove entries for variables that are now read-in from the netcdf input file. `namelist.input` was also modified to include a new entry `grid_filename`, which is the directory/name of the input netcdf file passed to `gridlist_type%ReadGridlist`

Changes were made to several of the initialization subroutines for the gridded derived data type members of `noahowpgrid_type`. Several of these subroutines were modified to take an instance of the `gridlist_type` as an argument, often to provide access to `n_x` and `n_y` for allocating allocatable arrays but in some cases. Note that land use values are transferred from `gridlist_type` to `domaingrid_type` when `gridlist_type` is given as an argument to `domaingrid_type%InitTransfer`.

# TESTING

The PR-modified Noah-owp model was successfully compiled on MacOS using GNU Fortran (Homebrew GCC 13.1.0) 13.1.0. 

Because the input netcdf file used for testing depicts homogenous vegtyp, lats, and longs with values identical to those listed in `run/namelist.input` of the main branch (i.e., containing the unmodified Noah-OM column model), the output from the unmodified column model should match the output from this PR-modified model for all grid cells. Thus, `test/analysis/compare_outputnc.py` was executed and all tests were passed.  

The unit tests (`test/noahowp_driver_test.f90`) were re-executed and output was normal.

# NOTES

I was unsure about the desired format/organization of the input netcdf file but moved forward with one possible format/organization with the belief that we can easily implement changes per PR feedback.

I have no problem doing a complete re-write of this PR if we decide this approach (i.e., mimicking namelist_type) is suboptimal.

# Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/)

2023-08-01 18:11 UTC, GreyEvenson-NOAA commented on src/Makefile
This file was updated to facilitate this PR (#74) *and* PR #71. I'm not sure why PR #71 worked without updates to this file but it did.

2023-08-04 14:07 UTC, SnowHydrology requested changes
@GreyEvenson-NOAA, thanks for getting this started. A few changes:

- Can you modify the `netcdf_dummy.nc` to have valid latitudes and longitudes, consistent with the provided `dx` and `dy` values?
- Can you also vary the land cover values within the file so that we can verify that the land cover values do indeed vary within the grid and that we get differing output based on land cover?
- In the changed `netcdf_dummy.nc` file, there should be one grid cell that matches the parameters of the test case (vegtyp, lat, lon, etc.), while the others differ per my recommended changes above.
- I'm not sure how I feel about the name `gridlist`. It's not a namelist, so there's no reason to keep the "list" part. Maybe change it to `gridinfo` or something like that.

2023-08-04 14:07 UTC, SnowHydrology commented on data/netcdf_dummy.nc
See suggested changes in my review comments.

2023-08-04 14:07 UTC, SnowHydrology commented on run/namelist.input
Is the plan to have all gridded values be in one NetCDF file or spread across multiple. If the latter, then you'll want to make the file name here more illustrative.

2023-08-04 14:40 UTC, GreyEvenson-NOAA commented on run/namelist.input
I'm going back and forth with this question. On one hand, I can see why having a single NetCDF file would be preferable as it will allow for NetCDF-defined dimensions to be shared across multiple NetCDF-defined variables. This could cut down on problems attributable to a model-user providing variables that do not share the same grid (?). On the other hand, we could expect a separate NetCDF file for every variable and write checks to stop the program if there is any difference in grid info across the provided grids. Having a separate NetCDF file and associated line in namelist.input for separate model variables also just seems more intuitive (word choice?) to me.

Do you have thoughts/preferences regarding this choice, @SnowHydrology ?

2023-08-08 20:08 UTC, GreyEvenson-NOAA commented on run/namelist.input
I got feedback from Scott on a standup advocating for using a single NetCDF file for each of the model's gridded input variables (e.g., one for land use, a second for soils, etc. etc.) but got feedback from Nels on slack advocating use of a single NetCDF for all gridded inputs. I can imagine scenarios in which a model-user would prefer either and so I don't have a firm opinion either way but revised the code expecting multiple files. 

Note that I believe the code should still work if the model-user simply puts all gridded variables in one file and gives the path/name to a single NetCDF input file on multiple lines of `namelist.input` (e.g., on separate lines for land use, soils, slops, etc.). This would lead to some sunk costs in opening/closing the file multiple times and reading dimensions multiple times but it's an option.

2023-08-08 20:42 UTC, GreyEvenson-NOAA commented
@SnowHydrology, I think we're ready for you to have another look. Note that I revised the PR-description to incorporate your comments. But to address the specific points in your previous comment:

- `netcdf_dummy.nc` now has valid lat/longs in agreement with provided dx and dy values following revisions to the script used in its creation (`test/analysis/create_dummy_netcdf.py`)
- The revised  `netcdf_dummy.nc` has the lat, long, and land use values from the test case (i.e., `run/namelist.input` in main branch) while all other grid cells have different lat, long, and land use values.
- I changed `gridlist_type` to `gridinfo_type`

2023-08-09 14:46 UTC, merged