Noah-OM gridded namelist.input refactor
NOAA-OWP/noah-owp-modular pull request #87
Opened 2023-09-21 15:15 UTC by GreyEvenson-NOAA

2023-09-22 13:44 UTC, GreyEvenson-NOAA commented
@SnowHydrology: @nmizukami was kind enough to volunteer to review this. However, I wanted to call your attention to this PR because (1) it refactors `namelist.input`, which seems important, and (2) it does not require that the `IST` variable (i.e., soil vs lake indicator variable) be read-in via NetCDF -- the PR instead initializes `IST` via `vegtyp` (land use). Let me know if you have thoughts on this.

2023-10-12 14:55 UTC, SnowHydrology reviewed
@GreyEvenson-NOAA, this looks good to me and the model runs correctly.

@nmizukami and @andywood, how do you feel about the variable names for the netcdf files in the namelist? Is that a good place or should they go somewhere else?

2023-10-12 15:52 UTC, andywood reviewed
my main two reactions are:
* I would avoid a generic name like 'netcdfin_filename' that doesn't given any sense of what the file contains, versus something descriptive/intuitive, eg 'param_filename' or 'static_input_filename' or 'attrib' etc.  I like the way summa separates parameters from attributes (all static but different in nature), where the param file data will get altered more often but the geophys attribs don't change unless the spatial/vertical configuration of the model changes.  

* as a rule, I don't like bulky config files, especially if they contain things that a user would not need to see or change very often (or at all).  So I would go back to just specifying the netcdf filename here, while hardwiring the convention for what variables in the netcdf file need to be named.  It cuts down on code and config file bloat.  many models do this (fixed input var names) because it's not an onerous user requirement that the user prepare the input file following some conventions:  eg, vegtyp, isltyp, soilcolor, slope, aazimuth, latitude, longitude, dx, dy (and no caps on Latitude, Long to be consistent).  we do want to allow users some control and flexibility but it's best to focus it on things that make a big difference either for them or their modeling options -- my opinions is that they will be fine if they don't have their own special input name for latitude.  Having some reasonable conventions can also make analysis across input files and configurations easier, as more things can be assumed.  

btw, nice to see some summa-style code and missingType variables included, e.g., 
if(name_att_dy /= stringMissing) then; this%name_att_dy = name_att_dy; else; write(*,'(A)') 'ERROR: required entry name_att_dy not found in namelist'; stop; end if
this code looks straight out of summa, possibly through naoki?

2023-10-12 18:24 UTC, nmizukami reviewed
Hi Grey,  

After looking at the namelist example (`namelist.input`), I agree with Andy's first comment on variable name for netcdf - `netcdfin_filename`.  This can be more specific name (I think this is easy to fix in this PR).

For the second comment from Andy,  if you make the NetCDF variable names hardcoded, you would need to add the lines to check if the variable exist in the netCDF given the name, using `nf90_inq_varid` (maybe another netCDF function?), and tell the user that netCDF variables need to be xxxx.  

or you provide the hardcoded default name and allow the user to overwrite them if user provide something other than default name in netCDF for some reason.  But, I am not sure if you can do optional namelist variables. 

For now, netCDF input variables are not too many, so looks ok, but if the list of variables increase, it will become unreasonable for the user to input them in the namelist. So I am leaning having default names.

2023-10-12 18:24 UTC, nmizukami commented on run/namelist.input
> +&netcdf_input
This could be renamed.  e.g., attributes or geophysical_attrs (maybe too long?)

2023-10-12 18:24 UTC, nmizukami commented on run/namelist.input
> + netcdfin_filename  = "../data/netcdf_input.nc"  ! directory/name of NetCDF file holding gridded model inputs
could rename `netcdfin_filename` to `attribute_netcdf` (or something like this)

2023-10-12 18:24 UTC, nmizukami commented on src/NamelistRead.f90
> +    namelist / netcdf_input    / netcdfin_filename,name_var_vegtyp,name_var_isltyp,name_var_soilcolor,&
consider modifying namelist group name and variable name for netcdf name

2023-10-12 19:25 UTC, nmizukami commented on src/RunModule.f90
>        end do
might be good to comment what is 1 and 2?   I think initializing lake or waterbody from land cover information makes sense to me (i guess this is called vegtype, so feel strange? but i think it is ok.  I guess noah traditionally uses vegetation type rather than land cover type?)

2023-10-12 19:41 UTC, andywood commented on run/namelist.input
> + netcdfin_filename  = "../data/netcdf_input.nc"  ! directory/name of NetCDF file holding gridded model inputs
I think the netcdf aspect is not too significant ... versus that it's a 'filename' and what it contains.  A hybrid could be used, too, eg 'attrib_nc_file' or something -- & you're right, these are attributes, not params.

2023-10-12 19:44 UTC, andywood commented on run/namelist.input
> +&netcdf_input
@naoki, I'd think a inq_varid call is needed regardless of whether the varname is user specified or not. 
you can get away without it but then can't trap the explicit error and message it as clearly.

2023-10-13 11:33 UTC, GreyEvenson-NOAA commented
I appreciate you all taking the time to look at this, @SnowHydrology, @andywood, and @nmizukami. 

I'll revise this PR to rename the netcdfin_filename to attrib_nc_file or something similar. I'll also hardcode the NetCDF variable, attribute, and dimension names and make sure that we have sufficient checks and error messages in case the user provides unexpected names/values. I'll additionally make sure to address anything else that you've identified in the comments above.

@andywood: regarding that SUMMA-style code, whomever wrote the NamelistRead subroutine gave us that gift. That's where I lifted it from!

Thanks again, all! Appreciate it.

2023-10-13 14:02 UTC, SnowHydrology requested changes
Thanks @nmizukami and @andywood for your feedback on the namelist. @GreyEvenson-NOAA, let me know when you've integrated their changes and I'll review again. Thanks!

2023-10-13 14:59 UTC, GreyEvenson-NOAA commented on run/namelist.input
> + netcdfin_filename  = "../data/netcdf_input.nc"  ! directory/name of NetCDF file holding gridded model inputs
Given this discussion, would you folks suggest that we rename the `NetCDFVarsType` module and the derived types that are defined within?  For example, the `NetCDFVarsType` module could be renamed the `BasinAttributesType` module or the `DomainAttributesType`? `netcdfvars_type` could be renamed `basinattributes_type` or `domainattrib_type`? Let me know if you have thoughts @andywood @nmizukami @SnowHydrology. I will default to making no change the module and derived type names.

2023-10-13 22:10 UTC, andywood commented on run/namelist.input
> + netcdfin_filename  = "../data/netcdf_input.nc"  ! directory/name of NetCDF file holding gridded model inputs
definitely -- the type should be more related to its significance (eg params, attributes, forcings etc) than the filetype they come from.  good call :).  In this case I thinking we're dealing with attributes, so an attrib_type would be good.  if there's a scale-related scope (eg global, basin, local) that could be part of the type name too.

2023-10-13 22:12 UTC, andywood commented
> I appreciate you all taking the time to look at this, @SnowHydrology, @andywood, and @nmizukami.
> 
> I'll revise this PR to rename the netcdfin_filename to attrib_nc_file or something similar. I'll also hardcode the NetCDF variable, attribute, and dimension names and make sure that we have sufficient checks and error messages in case the user provides unexpected names/values. I'll additionally make sure to address anything else that you've identified in the comments above.
> 
> @andywood: regarding that SUMMA-style code, whomever wrote the NamelistRead subroutine gave us that gift. That's where I lifted it from!
> 
> Thanks again, all! Appreciate it.

Could have been me pulling that in -- a sad part of fractured attention to too many projects is that I don't remember!

2023-10-16 20:01 UTC, GreyEvenson-NOAA commented on src/RunModule.f90
>        end do
Probably a good idea -- I added comments to describe IST value meaning.

Yes, the vegtyp = land use did seem odd to me initially. I don't know the backstory but maybe because the model was initially aiming to get vegetation phenology correct rather than human activities such as agriculture (?).

2023-10-16 20:06 UTC, GreyEvenson-NOAA commented on src/NamelistRead.f90
> +    namelist / netcdf_input    / netcdfin_filename,name_var_vegtyp,name_var_isltyp,name_var_soilcolor,&
This got changed to: `namelist / attributes        / attributes_filename`. Let me know if you think the names could be improved.

2023-10-16 20:13 UTC, GreyEvenson-NOAA commented on run/namelist.input
> + netcdfin_filename  = "../data/netcdf_input.nc"  ! directory/name of NetCDF file holding gridded model inputs
I changed lots of names in revising the PR:

`NetCDFVarsType.f90` -> `AttributesType.f90`
`netcdfvars_type` -> `attributes_type`
`netcdfin_filename` -> `attributes_filename`

However, I'm not married to these. I'd be happy to change them again if folks think it would be helpful.

2023-10-16 21:05 UTC, andywood commented
This all looks good to me, Grey :)

On Mon, Oct 16, 2023 at 2:13 PM GreyEvenson-NOAA ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In run/namelist.input
> <https://github.com/NOAA-OWP/noah-owp-modular/pull/87#discussion_r1361218481>
> :
>
> > @@ -51,8 +45,19 @@
>   nsnow            = 3               ! number of snow levels
>   nveg             = 20              ! number of vegetation types
>   croptype         = 0               ! crop type (0 = no crops; this option is currently inactive)
> - sfctyp           = 1               ! land surface type, 1:soil, 2:lake
> - soilcolor        = 4               ! soil color code
> +/
> +
> +&netcdf_input
> + netcdfin_filename  = "../data/netcdf_input.nc"  ! directory/name of NetCDF file holding gridded model inputs
>
> I changed lots of names in revising the PR:
>
> NetCDFVarsType.f90 -> AttributesType.f90
> netcdfvars_type -> attributes_type
> netcdfin_filename -> attributes_filename
>
> However, I'm not married to these. I'd be happy to change them again if
> folks think it would be helpful.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-OWP/noah-owp-modular/pull/87#discussion_r1361218481>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABIKARI7N5UAY34ASBS474TX7WIONAVCNFSM6AAAAAA5BXC2T2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOBQHA4DENZSHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-17 13:15 UTC, GreyEvenson-NOAA commented
@SnowHydrology, I believe we're ready for you to have another look. @andywood seemed to approve of the changes. @nmizukami, let me know if you see anything else we can improve upon.

Thanks again for all your time in reviewing this!

2023-10-17 13:22 UTC, GreyEvenson-NOAA commented on data/netcdf_input.nc
The latitude and longitude dimensions and variables are now lower-case to be consistent with names.

2023-10-17 13:23 UTC, GreyEvenson-NOAA commented on test/analysis/create_dummy_netcdf_singlefile.py
Modified the script to create the input netcdf file with lower case latitude and longitude names.

2023-10-17 13:39 UTC, nmizukami approved these changes
Hi Grey,  I put one minor comment but I don't see anything else to add.  thank you for incorporating this!

2023-10-17 13:39 UTC, nmizukami commented on src/AttributesType.f90
> +      if(attributes_2d%data(1,1) == realMissing) then; write(*,*) 'ERROR : problem reading ''',trim(varname),''' from ''',trim(filename),''''; stop; end if
One last minor thing here...    I think maybe add default (unlikely to come here in this situation, but just for completeness and good practice)
 
```
  class default
     write(*,*) 'error message'; stop ": ERROR EXIT"
  end select
```

also the same for previous select type clause.

2023-10-17 14:02 UTC, GreyEvenson-NOAA commented on src/AttributesType.f90
> +      if(attributes_2d%data(1,1) == realMissing) then; write(*,*) 'ERROR : problem reading ''',trim(varname),''' from ''',trim(filename),''''; stop; end if
Nice catch. I just added the `class default` to both of the `select type` statements here.

2023-11-02 13:25 UTC, SnowHydrology approved these changes
Model runs with expected values and unit tests pass

2023-11-02 13:25 UTC, merged