Add support for NWM 3.0 baseline variables
NOAA-OWP/noah-owp-modular pull request #91
Opened 2023-11-02 15:05 UTC by GreyEvenson-NOAA

2023-11-02 19:27 UTC, GreyEvenson-NOAA commented
@SnowHydrology, @ajkhattak, @rlmcdaniel: I tagged you all in case you'd like to look this over.

2023-11-03 19:27 UTC, GreyEvenson-NOAA commented
@SnowHydrology, something that I should have mentioned: I did *not* implement the newly added variables in the BMI set_value functions; I only implemented the variables in the get_value functions. Let me know if you think we should include them in the set_value functions.

2023-11-16 21:12 UTC, SnowHydrology commented
@GreyEvenson-NOAA, I tested these updates and ran into a couple hiccups.

1. When I run the module in NextGen, I get really large output values for `SNOWT_AVG` and `GH`
<img width="708" alt="image" src="https://github.com/NOAA-OWP/noah-owp-modular/assets/32177682/4c8fc1bc-576a-456d-bc52-286f7d8f8596">
For SNOWT_AVG, this may be a result of `ISNOW = 0` because there is no snowpack temperature to report. The massive value generally means the variable has been initialized with `huge()` and then never updated with real data. 
2. When I run the model in standalone mode, I get reasonable output for the `STC` var (from which `SNOWT_AVG` is derived). When `ISNOW = 0` the `STC` values for snow elements are all 0. Additionally, `SNOWT_AVG` returns a reasonable value in the unit test when snow is present.
<img width="375" alt="image" src="https://github.com/NOAA-OWP/noah-owp-modular/assets/32177682/87680f7a-4239-4037-9e4b-5defa54309e3">
However, `GH` still returns the `huge()` value.
<img width="351" alt="image" src="https://github.com/NOAA-OWP/noah-owp-modular/assets/32177682/646277ba-64d3-452c-96ce-816ab7487910">

2023-11-16 21:13 UTC, SnowHydrology requested changes
Please see comment.

2023-11-17 15:04 UTC, GreyEvenson-NOAA commented
Appreciate the catches! 

I fixed `GH` by adding a line of code to calculate `GH`. This line was in the gridded branch but I forgot to add it into this branch by mistake.

I fixed `SNOWT_AVG` by changing the way that `SNOWT_AVG` is calculated. We were previously calculating `SNOWT_AVG` as:

```
   if (sum(water%SNICE(-levels%nsnow+1:0) + water%SNLIQ(-levels%nsnow+1:0)).gt.0.) then
      energy%SNOWT_AVG = SUM(energy%STC(-levels%nsnow+1:0)*(water%SNICE(-levels%nsnow+1:0)+water%SNLIQ(-levels%nsnow+1:0))) / &
                         SUM(water%SNICE(-levels%nsnow+1:0)+water%SNLIQ(-levels%nsnow+1:0))
   else
      energy%SNOWT_AVG = huge(1.)
   end if
```
However, SNOWT_AVG is now calculated as:

```
   if (sum(water%SNICE(-levels%nsnow+1:0) + water%SNLIQ(-levels%nsnow+1:0)).gt.0.) then
      energy%SNOWT_AVG = SUM(energy%STC(-levels%nsnow+1:0)*(water%SNICE(-levels%nsnow+1:0)+water%SNLIQ(-levels%nsnow+1:0))) / &
                         SUM(water%SNICE(-levels%nsnow+1:0)+water%SNLIQ(-levels%nsnow+1:0))
   else
      energy%SNOWT_AVG = realMissing
   end if
```
where realMissing = -999999.0. Hence, when there is no snow/ice, SNOWT_AVG should be -999999.0 instead of huge(). I did this because the [WRF HYDRO NWM repo](https://github.com/NCAR/wrf_hydro_nwm_public/blob/5d9e489fed01ed7cbd6b5680616ee37812a7137a/src/Land_models/NoahMP/phys/module_sf_noahmpdrv.F#L1386) has `SNOWT_AVG` being set to `undefined_value`, which was defined as `REAL, PARAMETER :: undefined_value = -1.E36`. This change will need to be made in the gridded branch as well but I'll wait for feedback before implementing the change.

2023-11-17 18:01 UTC, GreyEvenson-NOAA commented
Okay, @SnowHydrology, I believe this is ready for you again. I re-ran the unit test and `GH` and `SNOWT_AVG` had valid values in [this unit test output](https://github.com/NOAA-OWP/noah-owp-modular/files/13395086/unit_test_output.txt). I also ran it via NextGen and verified that `GH` has valid values and that `SNOWT_AVG` has a value of -9999999.0 where `ISNOW` = 0.

2023-11-28 17:09 UTC, SnowHydrology approved these changes
Tested in standalone and NextGen, previous issues fixed.

2023-11-28 17:09 UTC, merged